"""'adding_nullable'

Revision ID: 066badbc77f9
Revises: 19130b639156
Create Date: 2023-08-31 12:22:07.902463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '066badbc77f9'
down_revision = '19130b639156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('post_title',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('post_body',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('post_intro',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('post_body',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('post_title',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
