"""'post_intro'

Revision ID: 19130b639156
Revises: e9e9612ffb11
Create Date: 2023-08-31 12:20:21.785208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19130b639156'
down_revision = 'e9e9612ffb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_intro', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('post_intro')

    # ### end Alembic commands ###
