"""'featured_image'

Revision ID: 9545b3f5da84
Revises: 066badbc77f9
Create Date: 2023-09-06 09:48:43.402717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9545b3f5da84'
down_revision = '066badbc77f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image', sa.String(200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('featured_image')

    # ### end Alembic commands ###
